### ISSUE TITLE
I thinks needed to update instagram_private_api

### ISSUE THREAD

**Issue by NabiKAZ** [taengstagram/instagram-livestream-downloader#26]
I get this error:
I thinks needed to update instagram_private_api

```
INSTAGRAM LIVESTREAM DOWNLOADER (v0.3.8) [python=2.7.5,linux2]
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Broadcast status is currently: interrupted
--------------------------------------------------------------------------------
Broadcast by: xxxxxxxxx         (111111111)     Type: Live
Viewers: 1              Started: 5m 42s ago
Dash URL: https://scontent-frt3-2.cdninstagram.com/hvideo-atn6/_nc_cat-101/v/xxxxxxxxxxxx
--------------------------------------------------------------------------------
Downloading into downloaded/20200712_xxxxxxxx_live_downloads ...
[i] To interrupt the download, press CTRL+C
Duplicate etag 3cf132ebe094b44d4f83c detected 5 time(s)
Broadcast Status Check: interrupted
^CDownload interrupted.
Recorded stream is missing 323 seconds
Assembling files....
Traceback (most recent call last):
  File "/usr/bin/livestream_dl", line 9, in <module>
    load_entry_point('instagram-livestream-downloader==0.3.8', 'console_scripts', 'livestream_dl')()
  File "/usr/lib/python2.7/site-packages/instagram_livestream_downloader-0.3.8-py2.7.egg/livestream_dl/__main__.py", line 5, in main
    run()
  File "/usr/lib/python2.7/site-packages/instagram_livestream_downloader-0.3.8-py2.7.egg/livestream_dl/download.py", line 575, in run
    cleartempfiles=(not userconfig.nocleanup))
  File "/usr/lib/python2.7/site-packages/instagram_private_api_extensions/live.py", line 369, in stitch
    raise ValueError('No stream ID found.')
ValueError: No stream ID found.
```

**Comment by NabiKAZ** [comment]
Fixed: https://github.com/taengstagram/instagram-livestream-downloader/pull/27
